### ISSUE TITLE
Launch Tasks

### ISSUE THREAD

**Issue by CyberDex** [pixijs/ui#42]
# Info

Below is a list of open issues / tasks that need to be complete before our global launch on the 30th

# Tasks

- [x] All P1/2 tickets are completed 
- [x] API is fully documented
- [x] Examples work with v7
- [x] README is updated
  - [x] Logo
  - [x] Installation Guide
  - [x] Usage
  - [x] Contributing Link (Copy from pixi and update)
  - [x] License
  - [x] Open Collective 
- [x] Website published to gh-pages
- [x] Official release on npm
- [x] Release notes on Github 
- [x] Announcement post prepared
